In [21]:
import numpy as np
np.random.seed(42)

In [22]:
def sigmoid(x):
    return 1/(1+np.exp(-x))


In [23]:
# Network size
N_input=4
N_hidden=3
N_output=2


In [24]:
# Make some fake data
X=np.random.randn(N_input)
print X.shape
print
weights_input_to_hidden=np.random.normal(0,scale=0.1,size=(N_input,N_hidden))
print weights_input_to_hidden
print 
weights_hidden_to_output=np.random.normal(0,scale=0.1,size=(N_hidden,N_output))
print weights_hidden_to_output

(4,)

[[-0.02341534 -0.0234137   0.15792128]
 [ 0.07674347 -0.04694744  0.054256  ]
 [-0.04634177 -0.04657298  0.02419623]
 [-0.19132802 -0.17249178 -0.05622875]]

[[-0.10128311  0.03142473]
 [-0.09080241 -0.14123037]
 [ 0.14656488 -0.02257763]]


In [25]:
# Make a forward pass through the network
hidden_layer_in=X.dot(weights_input_to_hidden)
hidden_layer_out=sigmoid(hidden_layer_in)
print hidden_layer_out.shape

output_layer_in=hidden_layer_out.dot(weights_hidden_to_output)
output_layer_out=sigmoid(output_layer_in)
print output_layer_out

(3,)
[ 0.49815196  0.48539772]
