In [1]:
import numpy as np


In [2]:
# Scalar
s=np.array(5)
print s.shape

()


In [3]:
# Vector is one dimentional data
v=np.array([1,2,3])
print v.shape

(3,)


In [4]:
print v[1:]

[2 3]


In [6]:
# Matrix
m=np.array([[1,2,3],[4,5,6],[7,8,9]])
print m.shape

(3, 3)


In [8]:
# Tensor: n dimentional data
t = np.array([[[[1],[2]],[[3],[4]],[[5],[6]]],[[[7],[8]],\
[[9],[10]],[[11],[12]]],[[[13],[14]],[[15],[16]],[[17],[17]]]])
print t.shape
print t[2][1][1][0]

(3, 3, 2, 1)
16


In [9]:
x=v.reshape(1,3)
print x

[[1 2 3]]


In [10]:
y=v.reshape(3,1)
print y

[[1]
 [2]
 [3]]


In [11]:
x2=v[None,:]
print x2

[[1 2 3]]


In [12]:
x3=v[:,None]
print x3

[[1]
 [2]
 [3]]
